import { getSupabaseClient } from '../supabase-client.js';
import { requireSession } from '../auth.js';
import { deleteNotification, listNotifications, markAllNotificationsRead, markNotificationRead } from '../data/notifications.js';
import { escapeHtml, formatDate } from '../ui.js';
const client = getSupabaseClient(); const session = await requireSession(client).catch(() => null);
if (!session) { location.href = 'login.html?next=notifications.html'; throw new Error('authentication required'); }
const list = document.getElementById('notifications'); const status = document.getElementById('status'); const markAll = document.getElementById('markAll');
const icons = { message:'✉', friend_request:'＋', friend_accepted:'✓', forum_reply:'↩', forum_like:'♥', item_vote:'$' };
const card = (item) => `<article class="notification${item.read_at ? '' : ' unread'}" data-id="${escapeHtml(item.id)}"><span class="notification-icon" aria-hidden="true">${icons[item.type] || '•'}</span><a class="notification-copy" href="${escapeHtml(item.href || 'notifications.html')}" data-open-notification><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.body || '')}</span><time datetime="${escapeHtml(item.created_at)}">${escapeHtml(formatDate(item.created_at))}</time></a><div class="notification-actions">${item.read_at ? '' : '<button class="btn mark-read" type="button">Mark read</button>'}<button class="btn delete-notification" type="button" aria-label="Delete notification">Delete</button></div></article>`;
async function load() { list.setAttribute('aria-busy','true'); const items = await listNotifications(client); list.innerHTML = items.map(card).join(''); list.removeAttribute('aria-busy'); status.textContent = items.length ? `${items.filter((item) => !item.read_at).length} unread` : 'You are all caught up.'; markAll.hidden = !items.some((item) => !item.read_at); document.querySelector('app-menu')?.refreshNotificationCount?.(); }
list.addEventListener('click', async (event) => { const row=event.target.closest('[data-id]'); if(!row)return; if(event.target.closest('[data-open-notification]')&&row.classList.contains('unread')) await markNotificationRead(client,row.dataset.id).catch(()=>{}); if(event.target.closest('.mark-read')){event.preventDefault();await markNotificationRead(client,row.dataset.id);await load();} if(event.target.closest('.delete-notification')){event.preventDefault();await deleteNotification(client,row.dataset.id);await load();} });
markAll.addEventListener('click',async()=>{markAll.disabled=true;try{await markAllNotificationsRead(client);await load();}finally{markAll.disabled=false;}});
load().catch((error)=>{console.error(error);list.removeAttribute('aria-busy');status.textContent='Unable to load notifications. Refresh and try again.';});
